name: TimeEssence
version: '0.1.0'
main: cn.lunadeer.mc.timeEssence.TimeEssence
api-version: '1.21'
author: lunadeer
description: A plugin that allows players to modify their personal time using packet manipulation
folia-supported: true

commands:
  time:
    description: Manage your personal time
    usage: /time <set|reset|freeze|unfreeze|info|help> [time]
    aliases: [ptime, personaltime]

permissions:
  timeessence.use:
    description: Allows use of time commands
    default: true
  timeessence.admin:
    description: Administrative permissions
    default: op
