name: TimeManager
version: '0.1.0'
main: cn.lunadeer.mc.timeManager.TimeManager
api-version: '1.21'
author: lunadeer
description: A plugin that allows players to modify their personal time using packet manipulation
folia-supported: true

commands:
  ptime:
    description: Manage your personal time
    usage: /ptime <set|reset|freeze|unfreeze|info|help> [time]

permissions:
  ptime.set:
    description: Allows use set command
    default: true
  ptime.freeze:
    description: Allows use freeze/unfreeze commands
    default: true

