name: Build Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    #	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Set up JDK 21"
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: "Build with Maven"
        run: |
          mvn clean package
      - name: "Stage"
        run: |
          mkdir -p staging
          mv target/TimeManager-*.jar staging/
      - name: "Build & test"
        run: |
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "done!"
      - name: "GitHub Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.build.outputs.TAG }}"
          prerelease: false
          files: |
            staging/*.jar
